server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jd?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CST
    username: root
    password: baiyufeng

#方式一
#mybatis:
#  config-location: classpath:mybatis-config.xml

#方式二
#mybatis:
#  mapper1-locations: classpath*:/mybatismapper/*.xml
#  type-aliases-package: com.mf.mybatis.domain